### ISSUE TITLE
error!

### ISSUE THREAD

**Issue by yunxiaozimeng** [atapour/monocularDepth-Inference#10]
Hi atapour ! thanks for your works  ,but i met an error when i inference images HERE is the error code

Traceback (most recent call last):
  File "run_test.py", line 15, in <module>
    for i, data in enumerate(dataset):
  File "E:\monocularDepth-Inference\data\__init__.py", line 40, in __iter__
    for i, data in enumerate(self.dataloader):
  File "F:\anaconda3\envs\fast_dp\lib\site-packages\torch\utils\data\dataloader.py", line 501, in __iter__
    return _DataLoaderIter(self)
  File "F:\anaconda3\envs\fast_dp\lib\site-packages\torch\utils\data\dataloader.py", line 289, in __init__
    w.start()
  File "F:\anaconda3\envs\fast_dp\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "F:\anaconda3\envs\fast_dp\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "F:\anaconda3\envs\fast_dp\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "F:\anaconda3\envs\fast_dp\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "F:\anaconda3\envs\fast_dp\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
        F:\anaconda3\envs\fast_dp\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "F:\anaconda3\envs\fast_dp\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

PLEASE TELL ME WHAT SHOULD I DO?

**Comment by atapour** [comment]
I have retested the code and it works fine. The issue is with your environment / packages.
